begin;

create extension if not exists pgtap with schema extensions;
set local search_path = public, extensions;

select plan(35);

select ok(
  to_regprocedure('public.begin_incremental_rating_rebuild(uuid,uuid)') is not null
    and to_regprocedure('public.apply_incremental_rating_rebuild(uuid,bigint,integer,jsonb,jsonb)') is not null,
  'canonical incremental rebuild RPCs exist'
);

select is(
  (
    select count(*)
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'rating_events'
      and column_name in (
        'before_games_played', 'after_games_played', 'game_id', 'game_number',
        'occurred_at', 'format', 'team', 'expected_score', 'actual_score',
        'points_for', 'points_against', 'rating_delta', 'expectation_residual',
        'point_delta'
      )
  ),
  14::bigint,
  'rating events expose the complete canonical fact'
);

select ok(
  exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'rating_events'
      and column_name = 'expected_score' and data_type = 'numeric'
      and numeric_precision = 10 and numeric_scale = 9
  )
    and exists (
      select 1 from information_schema.columns
      where table_schema = 'public' and table_name = 'rating_events'
        and column_name = 'actual_score' and data_type = 'smallint'
    ),
  'expectation and result use canonical numeric types'
);

select is(
  (
    select count(*)
    from information_schema.columns
    where table_schema = 'public' and table_name = 'rating_events'
      and column_name in ('before_rating', 'before_rd', 'after_rating', 'after_rd')
      and numeric_precision = 10 and numeric_scale = 4
  ),
  4::bigint,
  'rating and RD persistence remains four decimal places'
);

select is(
  (
    select count(*)
    from information_schema.columns
    where table_schema = 'public' and table_name = 'rating_events'
      and column_name in (
        'before_games_played', 'after_games_played', 'game_id', 'game_number',
        'occurred_at', 'format', 'team', 'expected_score', 'actual_score',
        'points_for', 'points_against'
      )
      and is_nullable = 'NO'
  ),
  11::bigint,
  'all canonical input columns are required'
);

select is(
  (
    select count(*)
    from information_schema.columns
    where table_schema = 'public' and table_name = 'rating_events'
      and column_name in ('rating_delta', 'expectation_residual', 'point_delta')
      and is_generated = 'ALWAYS'
  ),
  3::bigint,
  'performance deltas are generated by Postgres'
);

select ok(
  exists (
    select 1
    from pg_constraint
    where conrelid = 'public.rating_events'::regclass
      and contype = 'f'
      and confrelid = 'public.match_games'::regclass
      and pg_get_constraintdef(oid) like 'FOREIGN KEY (game_id)%'
  ),
  'canonical game identity references match_games'
);

select ok(
  exists (select 1 from pg_constraint where conrelid = 'public.rating_events'::regclass and conname = 'rating_events_expected_score_check')
    and exists (select 1 from pg_constraint where conrelid = 'public.rating_events'::regclass and conname = 'rating_events_actual_score_check')
    and exists (select 1 from pg_constraint where conrelid = 'public.rating_events'::regclass and conname = 'rating_events_points_check')
    and exists (select 1 from pg_constraint where conrelid = 'public.rating_events'::regclass and conname = 'rating_events_games_played_step_check'),
  'canonical fact checks are installed'
);

select ok(
  exists (
    select 1 from pg_indexes
    where schemaname = 'public' and tablename = 'rating_events'
      and indexname = 'rating_events_group_game_user_key' and indexdef like 'CREATE UNIQUE INDEX%'
  ),
  'game and player form the canonical identity within a group'
);

select ok(
  exists (
    select 1 from pg_indexes
    where schemaname = 'public' and tablename = 'rating_events'
      and indexname = 'rating_events_group_sequence_key' and indexdef like 'CREATE UNIQUE INDEX%'
  ),
  'event sequence is globally unique within a group'
);

select ok(
  exists (select 1 from pg_indexes where schemaname = 'public' and tablename = 'rating_events' and indexname = 'rating_events_group_user_occurred_idx'),
  'player chronology has a supporting index'
);

select ok(
  exists (select 1 from pg_indexes where schemaname = 'public' and tablename = 'rating_events' and indexname = 'rating_events_group_game_team_idx'),
  'game and team analytics have a supporting index'
);

select ok(
  has_function_privilege('service_role', 'public.begin_incremental_rating_rebuild(uuid,uuid)', 'EXECUTE')
    and has_function_privilege('service_role', 'public.apply_incremental_rating_rebuild(uuid,bigint,integer,jsonb,jsonb)', 'EXECUTE'),
  'service role can execute canonical rebuild RPCs'
);

select ok(
  not has_function_privilege('anon', 'public.begin_incremental_rating_rebuild(uuid,uuid)', 'EXECUTE')
    and not has_function_privilege('authenticated', 'public.begin_incremental_rating_rebuild(uuid,uuid)', 'EXECUTE')
    and not has_function_privilege('anon', 'public.apply_incremental_rating_rebuild(uuid,bigint,integer,jsonb,jsonb)', 'EXECUTE')
    and not has_function_privilege('authenticated', 'public.apply_incremental_rating_rebuild(uuid,bigint,integer,jsonb,jsonb)', 'EXECUTE'),
  'clients cannot execute canonical rebuild RPCs'
);

select ok(
  not has_function_privilege('service_role', 'public.begin_rating_rebuild(uuid,uuid)', 'EXECUTE')
    and not has_function_privilege('service_role', 'public.apply_rating_rebuild(uuid,bigint,jsonb,jsonb)', 'EXECUTE'),
  'legacy full-history worker RPCs are disabled'
);

select ok(
  (select relrowsecurity from pg_class where oid = 'public.rating_events'::regclass),
  'rating events retain row-level security'
);

insert into public.profiles (id, display_name, first_name, last_name)
values
  ('c1111111-1111-4111-8111-111111111111', 'Canonical One', 'Canonical', 'One'),
  ('c2222222-2222-4222-8222-222222222222', 'Canonical Two', 'Canonical', 'Two');

insert into public.groups (id, owner_user_id, name, rating_input_version)
values ('caaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa', 'c1111111-1111-4111-8111-111111111111', 'Canonical Ladder', 1);

insert into public.group_memberships (group_id, user_id, role, status)
values
  ('caaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa', 'c1111111-1111-4111-8111-111111111111', 'owner', 'active'),
  ('caaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa', 'c2222222-2222-4222-8222-222222222222', 'member', 'active');

insert into public.matches (id, group_id, created_by_user_id, submitted_at)
values (
  'cbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb',
  'caaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',
  'c1111111-1111-4111-8111-111111111111',
  '2026-08-19T18:00:00Z'
);

insert into public.match_revisions (id, match_id, version, submitted_by_user_id, format)
values (
  'cccccccc-cccc-4ccc-8ccc-cccccccccccc',
  'cbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb',
  1,
  'c1111111-1111-4111-8111-111111111111',
  'singles'
);

insert into public.match_participants (revision_id, user_id, team, slot)
values
  ('cccccccc-cccc-4ccc-8ccc-cccccccccccc', 'c1111111-1111-4111-8111-111111111111', 'A', 1),
  ('cccccccc-cccc-4ccc-8ccc-cccccccccccc', 'c2222222-2222-4222-8222-222222222222', 'B', 1);

insert into public.match_games (id, revision_id, game_number, team_a_score, team_b_score, winner_team)
values ('cddddddd-dddd-4ddd-8ddd-dddddddddddd', 'cccccccc-cccc-4ccc-8ccc-cccccccccccc', 1, 21, 18, 'A');

update public.matches
set active_revision_id = 'cccccccc-cccc-4ccc-8ccc-cccccccccccc'
where id = 'cbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb';

insert into public.rating_rebuild_jobs (
  id, group_id, from_match_id, status, created_by_user_id, target_version,
  dispatch_token, dispatch_lease_expires_at
)
values (
  'ceeeeeee-eeee-4eee-8eee-eeeeeeeeeeee',
  'caaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',
  'cbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb',
  'queued',
  'c1111111-1111-4111-8111-111111111111',
  1,
  'cfffffff-ffff-4fff-8fff-ffffffffffff',
  now() + interval '1 minute'
);

create temporary table canonical_test_state (value jsonb not null) on commit drop;
insert into canonical_test_state
select public.begin_incremental_rating_rebuild(
  'ceeeeeee-eeee-4eee-8eee-eeeeeeeeeeee',
  'cfffffff-ffff-4fff-8fff-ffffffffffff'
);

select is(
  (select value->>'groupId' from canonical_test_state),
  'caaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',
  'incremental begin returns the locked group'
);

select is(
  (select (value->>'prefixEventCount')::integer from canonical_test_state),
  0,
  'a group without canonical facts starts at prefix zero'
);

select ok(
  (select value#>>'{history,0,games,0,gameId}' from canonical_test_state) = 'cddddddd-dddd-4ddd-8ddd-dddddddddddd'
    and (select (value#>>'{history,0,games,0,gameNumber}')::integer from canonical_test_state) = 1
    and (select value#>>'{history,0,games,0,winnerTeam}' from canonical_test_state) = 'A',
  'incremental history carries canonical game identity and selected winner'
);

select is(
  (
    public.apply_incremental_rating_rebuild(
      'ceeeeeee-eeee-4eee-8eee-eeeeeeeeeeee',
      1,
      0,
      '[
        {"userId":"c1111111-1111-4111-8111-111111111111","rating":1662.3109,"rd":290.3189,"volatility":0.05999968,"gamesPlayed":1,"rank":1},
        {"userId":"c2222222-2222-4222-8222-222222222222","rating":1337.6891,"rd":290.3189,"volatility":0.05999968,"gamesPlayed":1,"rank":2}
      ]'::jsonb,
      '[
        {"matchId":"cbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb","revisionId":"cccccccc-cccc-4ccc-8ccc-cccccccccccc","gameId":"cddddddd-dddd-4ddd-8ddd-dddddddddddd","gameNumber":1,"occurredAt":"2026-08-19T18:00:00Z","format":"singles","team":"A","userId":"c1111111-1111-4111-8111-111111111111","sequence":1,"expectedScore":0.5,"actualScore":1,"pointsFor":21,"pointsAgainst":18,"before":{"rating":1500,"rd":350,"volatility":0.06,"gamesPlayed":0},"after":{"rating":1662.3109,"rd":290.3189,"volatility":0.05999968,"gamesPlayed":1}},
        {"matchId":"cbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb","revisionId":"cccccccc-cccc-4ccc-8ccc-cccccccccccc","gameId":"cddddddd-dddd-4ddd-8ddd-dddddddddddd","gameNumber":1,"occurredAt":"2026-08-19T18:00:00Z","format":"singles","team":"B","userId":"c2222222-2222-4222-8222-222222222222","sequence":2,"expectedScore":0.5,"actualScore":0,"pointsFor":18,"pointsAgainst":21,"before":{"rating":1500,"rd":350,"volatility":0.06,"gamesPlayed":0},"after":{"rating":1337.6891,"rd":290.3189,"volatility":0.05999968,"gamesPlayed":1}}
      ]'::jsonb
    )->>'status'
  ),
  'completed',
  'validated canonical suffix applies atomically'
);

select is(
  (select count(*) from public.rating_events where group_id = 'caaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa'),
  2::bigint,
  'one event exists for each active game participant'
);

select ok(
  exists (
    select 1 from public.rating_events
    where group_id = 'caaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa'
      and user_id = 'c1111111-1111-4111-8111-111111111111'
      and rating_delta = 162.3109
      and expectation_residual = 0.5
      and point_delta = 3
  ),
  'generated performance deltas have player-oriented values'
);

select is(
  (select count(*) from public.group_rating_states where group_id = 'caaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa'),
  2::bigint,
  'canonical apply replaces current rating states'
);

select is(
  (select rating_applied_version from public.groups where id = 'caaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa'),
  1::bigint,
  'canonical apply advances the single freshness marker'
);

insert into public.matches (id, group_id, created_by_user_id, submitted_at)
values (
  'd1111111-1111-4111-8111-111111111111',
  'caaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',
  'c1111111-1111-4111-8111-111111111111',
  '2026-08-19T19:00:00Z'
);

insert into public.match_revisions (id, match_id, version, submitted_by_user_id, format)
values (
  'd2222222-2222-4222-8222-222222222222',
  'd1111111-1111-4111-8111-111111111111',
  1,
  'c1111111-1111-4111-8111-111111111111',
  'singles'
);

insert into public.match_participants (revision_id, user_id, team, slot)
values
  ('d2222222-2222-4222-8222-222222222222', 'c1111111-1111-4111-8111-111111111111', 'A', 1),
  ('d2222222-2222-4222-8222-222222222222', 'c2222222-2222-4222-8222-222222222222', 'B', 1);

insert into public.match_games (id, revision_id, game_number, team_a_score, team_b_score, winner_team)
values ('d3333333-3333-4333-8333-333333333333', 'd2222222-2222-4222-8222-222222222222', 1, 17, 21, 'B');

update public.matches
set active_revision_id = 'd2222222-2222-4222-8222-222222222222'
where id = 'd1111111-1111-4111-8111-111111111111';

update public.groups
set rating_input_version = 2
where id = 'caaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa';

insert into public.rating_rebuild_jobs (
  id, group_id, from_match_id, status, created_by_user_id, target_version,
  dispatch_token, dispatch_lease_expires_at
)
values (
  'd4444444-4444-4444-8444-444444444444',
  'caaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',
  'd1111111-1111-4111-8111-111111111111',
  'queued',
  'c1111111-1111-4111-8111-111111111111',
  2,
  'd5555555-5555-4555-8555-555555555555',
  now() + interval '1 minute'
);

create temporary table suffix_test_state (value jsonb not null) on commit drop;
insert into suffix_test_state
select public.begin_incremental_rating_rebuild(
  'd4444444-4444-4444-8444-444444444444',
  'd5555555-5555-4555-8555-555555555555'
);

select is(
  (select (value->>'prefixEventCount')::integer from suffix_test_state),
  2,
  'append-only replay preserves the complete canonical prefix'
);

select is(
  (select jsonb_array_length(value->'initialRatings') from suffix_test_state),
  2,
  'append-only replay seeds each player from the latest prefix event'
);

select ok(
  (select jsonb_array_length(value->'history') from suffix_test_state) = 1
    and (select value#>>'{history,0,id}' from suffix_test_state) = 'd1111111-1111-4111-8111-111111111111',
  'append-only replay returns only the dirty suffix'
);

update public.rating_events
set points_for = 20
where group_id = 'caaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa' and sequence = 1;

truncate suffix_test_state;
insert into suffix_test_state
select public.begin_incremental_rating_rebuild(
  'd4444444-4444-4444-8444-444444444444',
  'd5555555-5555-4555-8555-555555555555'
);

select ok(
  (select (value->>'prefixEventCount')::integer from suffix_test_state) = 0
    and (select jsonb_array_length(value->'history') from suffix_test_state) = 2,
  'invalid canonical prefix state falls back to a full replay'
);

update public.rating_events
set points_for = 21
where group_id = 'caaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa' and sequence = 1;

update public.rating_rebuild_jobs
set from_match_id = 'cbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb'
where id = 'd4444444-4444-4444-8444-444444444444';

truncate suffix_test_state;
insert into suffix_test_state
select public.begin_incremental_rating_rebuild(
  'd4444444-4444-4444-8444-444444444444',
  'd5555555-5555-4555-8555-555555555555'
);

select ok(
  (select (value->>'prefixEventCount')::integer from suffix_test_state) = 0
    and (select jsonb_array_length(value->'history') from suffix_test_state) = 2,
  'an earlier dirty boundary includes every locked successor match'
);

insert into public.match_revisions (id, match_id, version, submitted_by_user_id, format)
values (
  'd6666666-6666-4666-8666-666666666666',
  'cbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb',
  2,
  'c1111111-1111-4111-8111-111111111111',
  'singles'
);

insert into public.match_participants (revision_id, user_id, team, slot)
values
  ('d6666666-6666-4666-8666-666666666666', 'c1111111-1111-4111-8111-111111111111', 'A', 1),
  ('d6666666-6666-4666-8666-666666666666', 'c2222222-2222-4222-8222-222222222222', 'B', 1);

insert into public.match_games (id, revision_id, game_number, team_a_score, team_b_score, winner_team)
values ('d7777777-7777-4777-8777-777777777777', 'd6666666-6666-4666-8666-666666666666', 1, 19, 21, 'B');

update public.matches
set active_revision_id = 'd6666666-6666-4666-8666-666666666666'
where id = 'cbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb';

truncate suffix_test_state;
insert into suffix_test_state
select public.begin_incremental_rating_rebuild(
  'd4444444-4444-4444-8444-444444444444',
  'd5555555-5555-4555-8555-555555555555'
);

select ok(
  (select value#>>'{history,0,revisionId}' from suffix_test_state) = 'd6666666-6666-4666-8666-666666666666'
    and not ((select value from suffix_test_state)->'history' @> '[{"revisionId":"cccccccc-cccc-4ccc-8ccc-cccccccccccc"}]'::jsonb),
  'incremental history contains only the active revision'
);

select throws_ok(
  $$
    select public.apply_incremental_rating_rebuild(
      'd4444444-4444-4444-8444-444444444444', 2, 0, '[]'::jsonb, '[]'::jsonb
    )
  $$,
  'MRVAL',
  'Invalid canonical rating events',
  'an incomplete canonical suffix is rejected before persisted state changes'
);

select ok(
  (select count(*) from public.rating_events where group_id = 'caaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa') = 2
    and (select count(*) from public.group_rating_states where group_id = 'caaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa') = 2
    and (select status from public.rating_rebuild_jobs where id = 'd4444444-4444-4444-8444-444444444444') = 'running',
  'a validation exception rolls back facts, ratings, and job completion together'
);

update public.groups
set rating_input_version = 2
where id = 'caaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa';

select is(
  (
    public.apply_incremental_rating_rebuild(
      'ceeeeeee-eeee-4eee-8eee-eeeeeeeeeeee',
      1,
      0,
      '[]'::jsonb,
      '[]'::jsonb
    )->>'status'
  ),
  'stale',
  'stale canonical projections are rejected'
);

select is(
  (select count(*) from public.rating_events where group_id = 'caaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa'),
  2::bigint,
  'stale rejection changes no canonical facts'
);

select is(
  (select status::text from public.rating_rebuild_jobs where id = 'ceeeeeee-eeee-4eee-8eee-eeeeeeeeeeee'),
  'completed',
  'stale retry changes no completed job state'
);

select * from finish();
rollback;
